CREATE DATABASE n7;

USE n7;

DROP DATABASE n7;

CREATE TABLE TURMA (
	IdTurma INT IDENTITY PRIMARY KEY,
	Turma VARCHAR (2),
);

CREATE TABLE ALUNO7 (
	IdAluno INT IDENTITY PRIMARY KEY,
	Nome VARCHAR (100),
	RA VARCHAR (20),
	IdTurma INT FOREIGN KEY REFERENCES TURMA (IdTurma)
);