CREATE DATABASE n3;

USE n3;

/* EXCLUIR TABELA */

DROP TABLE AUTOR;

DROP TABLE PUPLICACAO;


CREATE TABLE AUTOR (
	Idautor INT IDENTITY PRIMARY KEY,
	Nome VARCHAR (100),
);




CREATE TABLE LIVRO (
	IdLivro INT IDENTITY PRIMARY KEY,
	DataPublicacao VARCHAR (8),
	Nome VARCHAR (100)
);

CREATE TABLE PUPLICACAO (
	IdPuplicacao INT IDENTITY PRIMARY KEY,
	Idautor INT FOREIGN KEY REFERENCES AUTOR (IdAutor),
	IdLivro INT FOREIGN KEY REFERENCES LIVRO (IdLivro)
);